/**
 * Lucide icon categories for the icon picker
 * Icons are organized by use case for landing pages
 */

export interface IconCategory {
  id: string
  label: string
  icons: string[]
}

/**
 * Popular icons shown at the top of the picker
 * Curated for landing page use cases
 */
export const POPULAR_ICONS = [
  'Star',
  'Heart',
  'Check',
  'Phone',
  'Mail',
  'MapPin',
  'Clock',
  'Calendar',
  'ShoppingCart',
  'CreditCard',
  'Award',
  'Shield',
  'Zap',
  'Target',
  'Users',
  'ArrowRight',
  'Download',
  'Play',
  'Gift',
  'Truck',
  'ThumbsUp',
  'MessageCircle',
  'Share2',
  'Eye',
  'Lock',
  'Unlock',
  'Bell',
  'Settings',
  'Search',
  'Home',
] as const

/**
 * Icon categories with labels in French
 */
export const ICON_CATEGORIES: IconCategory[] = [
  {
    id: 'contact',
    label: 'Contact',
    icons: [
      'Mail',
      'Phone',
      'PhoneCall',
      'PhoneIncoming',
      'PhoneOutgoing',
      'MapPin',
      'Map',
      'Navigation',
      'Clock',
      'Calendar',
      'CalendarDays',
      'User',
      'Users',
      'UserPlus',
      'Contact',
      'AtSign',
      'Globe',
      'Building',
      'Building2',
      'Home',
      'Landmark',
    ],
  },
  {
    id: 'actions',
    label: 'Actions',
    icons: [
      'Check',
      'CheckCircle',
      'CheckCircle2',
      'X',
      'XCircle',
      'Plus',
      'PlusCircle',
      'Minus',
      'MinusCircle',
      'ArrowRight',
      'ArrowLeft',
      'ArrowUp',
      'ArrowDown',
      'ChevronRight',
      'ChevronLeft',
      'ChevronUp',
      'ChevronDown',
      'Download',
      'Upload',
      'ExternalLink',
      'Link',
      'Link2',
      'Send',
      'Share',
      'Share2',
      'Copy',
      'Clipboard',
      'ClipboardCheck',
      'Edit',
      'Edit2',
      'Trash2',
      'RefreshCw',
      'RotateCw',
      'RotateCcw',
    ],
  },
  {
    id: 'ecommerce',
    label: 'E-commerce',
    icons: [
      'ShoppingCart',
      'ShoppingBag',
      'CreditCard',
      'Wallet',
      'Banknote',
      'DollarSign',
      'Euro',
      'Package',
      'PackageOpen',
      'Truck',
      'Gift',
      'Tag',
      'Tags',
      'Percent',
      'Receipt',
      'Store',
      'BarChart',
      'BarChart2',
      'BarChart3',
      'PieChart',
      'TrendingUp',
      'TrendingDown',
      'Boxes',
      'Box',
      'Archive',
    ],
  },
  {
    id: 'social',
    label: 'Social',
    icons: [
      'Heart',
      'HeartHandshake',
      'ThumbsUp',
      'ThumbsDown',
      'Star',
      'Sparkles',
      'Award',
      'Trophy',
      'Medal',
      'MessageCircle',
      'MessageSquare',
      'MessagesSquare',
      'Quote',
      'Share2',
      'Forward',
      'Smile',
      'Frown',
      'Meh',
      'PartyPopper',
      'Cake',
      'HandHeart',
      'Handshake',
    ],
  },
  {
    id: 'media',
    label: 'Média',
    icons: [
      'Play',
      'PlayCircle',
      'Pause',
      'PauseCircle',
      'Video',
      'VideoOff',
      'Film',
      'Camera',
      'Image',
      'Images',
      'ImagePlus',
      'Music',
      'Music2',
      'Mic',
      'Mic2',
      'Volume2',
      'VolumeX',
      'Headphones',
      'Radio',
      'Tv',
      'Monitor',
      'Smartphone',
      'Tablet',
    ],
  },
  {
    id: 'business',
    label: 'Business',
    icons: [
      'Briefcase',
      'Building',
      'Building2',
      'Factory',
      'Landmark',
      'Award',
      'Target',
      'Goal',
      'TrendingUp',
      'LineChart',
      'PieChart',
      'Presentation',
      'FileText',
      'FileCheck',
      'Files',
      'FolderOpen',
      'Inbox',
      'Send',
      'Lightbulb',
      'Rocket',
      'Gauge',
      'Settings',
      'Cog',
      'Wrench',
      'Hammer',
    ],
  },
  {
    id: 'security',
    label: 'Sécurité',
    icons: [
      'Shield',
      'ShieldCheck',
      'ShieldAlert',
      'Lock',
      'Unlock',
      'Key',
      'KeyRound',
      'Eye',
      'EyeOff',
      'Fingerprint',
      'ScanFace',
      'UserCheck',
      'BadgeCheck',
      'CheckCircle2',
      'CircleAlert',
      'AlertTriangle',
      'AlertCircle',
      'Ban',
      'ShieldOff',
    ],
  },
  {
    id: 'nature',
    label: 'Nature',
    icons: [
      'Leaf',
      'TreeDeciduous',
      'TreePine',
      'Flower',
      'Flower2',
      'Sprout',
      'Sun',
      'Moon',
      'Cloud',
      'CloudRain',
      'CloudSun',
      'Snowflake',
      'Droplet',
      'Droplets',
      'Flame',
      'Waves',
      'Wind',
      'Mountain',
      'MountainSnow',
      'Sunrise',
      'Sunset',
      'Rainbow',
      'Thermometer',
    ],
  },
  {
    id: 'transport',
    label: 'Transport',
    icons: [
      'Car',
      'CarFront',
      'Truck',
      'Bus',
      'Train',
      'Plane',
      'PlaneTakeoff',
      'PlaneLanding',
      'Ship',
      'Anchor',
      'Bike',
      'Footprints',
      'Navigation',
      'Compass',
      'Map',
      'MapPin',
      'Route',
      'Milestone',
      'Fuel',
      'ParkingCircle',
    ],
  },
  {
    id: 'food',
    label: 'Restauration',
    icons: [
      'Utensils',
      'UtensilsCrossed',
      'ChefHat',
      'CookingPot',
      'Soup',
      'Pizza',
      'Salad',
      'Sandwich',
      'Croissant',
      'Cake',
      'IceCream',
      'Coffee',
      'Wine',
      'Beer',
      'Milk',
      'Apple',
      'Cherry',
      'Grape',
      'Carrot',
      'Egg',
      'Fish',
      'Beef',
    ],
  },
  {
    id: 'health',
    label: 'Santé',
    icons: [
      'Heart',
      'HeartPulse',
      'Activity',
      'Stethoscope',
      'Pill',
      'Syringe',
      'Thermometer',
      'Cross',
      'Hospital',
      'Ambulance',
      'Brain',
      'Dna',
      'Microscope',
      'TestTube',
      'Bone',
      'Hand',
      'Ear',
      'Eye',
      'Footprints',
      'Accessibility',
      'PersonStanding',
      'Dumbbell',
      'Timer',
    ],
  },
  {
    id: 'time',
    label: 'Temps',
    icons: [
      'Clock',
      'Clock1',
      'Clock2',
      'Clock3',
      'Clock4',
      'Clock5',
      'Clock6',
      'Clock7',
      'Clock8',
      'Clock9',
      'Clock10',
      'Clock11',
      'Clock12',
      'Timer',
      'TimerOff',
      'TimerReset',
      'Hourglass',
      'History',
      'Calendar',
      'CalendarDays',
      'CalendarCheck',
      'CalendarPlus',
      'Alarm',
      'AlarmClock',
      'Watch',
    ],
  },
]

/**
 * Get all icons from all categories (flattened)
 */
export function getAllCategorizedIcons(): string[] {
  const allIcons = new Set<string>()
  for (const category of ICON_CATEGORIES) {
    for (const icon of category.icons) {
      allIcons.add(icon)
    }
  }
  return Array.from(allIcons)
}

/**
 * Get category by icon name
 */
export function getCategoryForIcon(iconName: string): string | null {
  for (const category of ICON_CATEGORIES) {
    if (category.icons.includes(iconName)) {
      return category.id
    }
  }
  return null
}
