/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            name: string;
                            /** @enum {string} */
                            version: "1.0.0";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth.login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/social/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth.socialLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth.refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth.me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth.logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["campaigns.index"];
        put?: never;
        post: operations["campaigns.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaign}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["campaigns.show"];
        put: operations["campaigns.update"];
        post?: never;
        delete: operations["campaigns.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaign}/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["campaigns.estimate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaign}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["campaigns.schedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaign}/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["campaigns.send"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaign}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["campaigns.cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaign}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["campaigns.stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaign}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["campaigns.export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interest-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["interestGroups.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner-pricings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["partner-pricings.index"];
        put?: never;
        post: operations["partner-pricings.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner-pricings/{partnerPricing}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["partner-pricings.show"];
        put: operations["partner-pricings.update"];
        post?: never;
        delete: operations["partner-pricings.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["partners.index"];
        put?: never;
        post: operations["partners.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partners/{partner}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["partners.show"];
        put: operations["partners.update"];
        post?: never;
        delete: operations["partners.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["shops.index"];
        put?: never;
        post: operations["shops.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shops/{shop}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["shops.show"];
        put: operations["shops.update"];
        post?: never;
        delete: operations["shops.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users.index"];
        put?: never;
        post: operations["users.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users.show"];
        put: operations["users.update"];
        post?: never;
        delete: operations["users.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthResource */
        AuthResource: {
            access_token: string;
            /** @enum {string} */
            token_type: "Bearer";
            expires_in: string;
            refresh_token: string;
            user: components["schemas"]["UserResource"];
        };
        /**
         * CampaignChannel
         * @enum {string}
         */
        CampaignChannel: "sms" | "email";
        /** CampaignResource */
        CampaignResource: {
            id: string;
            partner_id: string;
            user_id: string;
            type: string;
            channel: string;
            status: string;
            is_demo: string;
            name: string;
            targeting: string;
            volume_estimated: string;
            volume_sent: string;
            message: string;
            sender: string;
            additional_phone: string;
            sms_count: string;
            short_url: string;
            scheduled_at: string;
            sent_at: string;
            unit_price: string;
            total_price: string;
            created_at: string;
            partner?: components["schemas"]["PartnerResource"];
            creator?: components["schemas"]["UserResource"];
            interest_groups?: components["schemas"]["InterestGroupResource"][];
        };
        /** CampaignStatsResource */
        CampaignStatsResource: {
            sent: number;
            delivered: number;
            undeliverable: number;
            rejected: number;
            expired: number;
            stop: number;
            clicks: number;
            deliverability_rate: number;
            ctr: number;
        };
        /**
         * CampaignType
         * @enum {string}
         */
        CampaignType: "prospection" | "fidelisation" | "comptage";
        /** InterestGroupResource */
        InterestGroupResource: {
            id: string;
            label: string;
            description: string;
            is_active: string;
            children?: components["schemas"]["InterestGroupResource"][];
            interests?: components["schemas"]["InterestResource"][];
        };
        /** InterestResource */
        InterestResource: {
            id: string;
            wellpack_id: string;
            label: string;
            type: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        /** PartnerPricingResource */
        PartnerPricingResource: {
            id: string;
            partner_id: string;
            name: string;
            volume_min: string;
            volume_max: string;
            router_price: string;
            data_price: string;
            ci_price: string;
            is_active: string;
            is_default: string;
            created_at: string;
            partner?: components["schemas"]["PartnerResource"];
        };
        /** PartnerResource */
        PartnerResource: {
            id: number;
            name: string;
            code: string;
            email: string;
            phone: string;
            address: string;
            city: string;
            zip_code: string;
            logo_url: string;
            euro_credits: string;
            is_active: boolean;
            /** Format: date-time */
            created_at: string | null;
            users_count?: number;
            shops_count?: number;
            users?: components["schemas"]["UserResource"][];
            shops?: components["schemas"]["ShopResource"][];
        };
        /** RefreshTokenRequest */
        RefreshTokenRequest: {
            refresh_token: string;
        };
        /** ScheduleCampaignRequest */
        ScheduleCampaignRequest: {
            /** Format: date-time */
            scheduled_at: string;
        };
        /** ShopResource */
        ShopResource: {
            id: string;
            partner_id: string;
            name: string;
            address: string;
            city: string;
            zip_code: string;
            phone: string;
            latitude: string;
            longitude: string;
            is_active: string;
            created_at: string;
            partner?: components["schemas"]["PartnerResource"];
        };
        /** SocialLoginRequest */
        SocialLoginRequest: {
            /** @enum {string} */
            provider: "google";
            token: string;
        };
        /** StorePartnerPricingRequest */
        StorePartnerPricingRequest: {
            partner_id: number;
            name: string;
            volume_min?: number | null;
            volume_max?: number | null;
            router_price: number;
            data_price: number;
            ci_price: number;
            is_active?: boolean | null;
            is_default?: boolean | null;
        };
        /** StorePartnerRequest */
        StorePartnerRequest: {
            name: string;
            code: string;
            /** Format: email */
            email?: string | null;
            phone?: string | null;
            address?: string | null;
            city?: string | null;
            zip_code?: string | null;
            /** Format: uri */
            logo_url?: string | null;
            euro_credits?: number | null;
            is_active?: boolean | null;
        };
        /** StoreUserRequest */
        StoreUserRequest: {
            firstname: string;
            lastname: string;
            /** Format: email */
            email: string;
            password: string;
            partner_id?: number | null;
            is_active?: boolean | null;
            /** @enum {string} */
            role: "admin" | "partner" | "merchant" | "employee";
        };
        /** UpdateCampaignRequest */
        UpdateCampaignRequest: {
            name?: string;
            type?: components["schemas"]["CampaignType"];
            channel?: components["schemas"]["CampaignChannel"];
            message?: string | null;
            sender?: string | null;
            /** Format: date-time */
            scheduled_at?: string | null;
            is_demo?: boolean;
            additional_phone?: string | null;
            targeting?: {
                age_min?: number | null;
                age_max?: number | null;
                geo?: string[] | null;
            };
        };
        /** UpdatePartnerPricingRequest */
        UpdatePartnerPricingRequest: {
            name?: string;
            volume_min?: number;
            volume_max?: number | null;
            router_price?: number;
            data_price?: number;
            ci_price?: number;
            is_active?: boolean | null;
            is_default?: boolean | null;
        };
        /** UpdatePartnerRequest */
        UpdatePartnerRequest: {
            name?: string;
            code?: string;
            /** Format: email */
            email?: string | null;
            phone?: string | null;
            address?: string | null;
            city?: string | null;
            zip_code?: string | null;
            /** Format: uri */
            logo_url?: string | null;
            euro_credits?: number | null;
            is_active?: boolean | null;
        };
        /** UpdateShopRequest */
        UpdateShopRequest: {
            name?: string;
            address?: string | null;
            city?: string | null;
            zip_code?: string | null;
            phone?: string | null;
            latitude?: number | null;
            longitude?: number | null;
            is_active?: boolean | null;
        };
        /** UpdateUserRequest */
        UpdateUserRequest: {
            firstname?: string;
            lastname?: string;
            /** Format: email */
            email?: string;
            password?: string;
            partner_id?: number | null;
            is_active?: boolean | null;
            /** @enum {string} */
            role?: "admin" | "partner" | "merchant" | "employee";
        };
        /** UserResource */
        UserResource: {
            id: number;
            firstname: string;
            lastname: string;
            full_name: string;
            email: string;
            partner_id: number | null;
            is_active: boolean;
            /** Format: date-time */
            created_at: string | null;
            roles: Record<string, never>;
            permissions: unknown[];
            partner?: components["schemas"]["PartnerResource"];
        };
    };
    responses: {
        /** @description Validation error */
        ValidationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Errors overview. */
                    message: string;
                    /** @description A detailed description of each field that failed validation. */
                    errors: {
                        [key: string]: string[];
                    };
                };
            };
        };
        /** @description Unauthenticated */
        AuthenticationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
        /** @description Authorization error */
        AuthorizationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
        /** @description Not found */
        ModelNotFoundException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "auth.login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description `AuthResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AuthResource"];
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        message: "Invalid credentials.";
                    };
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        message: "Your account has been deactivated.";
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.socialLogin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SocialLoginRequest"];
            };
        };
        responses: {
            /** @description `AuthResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AuthResource"];
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        message: "Invalid social token.";
                    };
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        message: "Your account has been deactivated.";
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description `AuthResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AuthResource"];
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        message: "Invalid refresh token.";
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `UserResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "auth.logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        message: "Successfully logged out.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "campaigns.index": {
        parameters: {
            query?: {
                page?: number;
                sort?: "name" | "-name" | "scheduled_at" | "-scheduled_at" | "sent_at" | "-sent_at" | "created_at" | "-created_at";
                include?: string;
                "filter[partner_id]"?: number;
                "filter[type]"?: "prospection" | "fidelisation" | "comptage";
                "filter[channel]"?: "sms" | "email";
                "filter[status]"?: "draft" | "scheduled" | "sending" | "sent" | "cancelled" | "failed";
                "filter[status][]"?: ("draft" | "scheduled" | "sending" | "sent" | "cancelled" | "failed")[];
                "filter[name]"?: string;
                "filter[created_at_from]"?: string;
                "filter[created_at_to]"?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `CampaignResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CampaignResource"][];
                        links: {
                            first: string | null;
                            last: string | null;
                            prev: string | null;
                            next: string | null;
                        };
                        meta: {
                            current_page: number;
                            from: number | null;
                            last_page: number;
                            /** @description Generated paginator links. */
                            links: {
                                url: string | null;
                                label: string;
                                active: boolean;
                            }[];
                            /** @description Base path for paginator generated URLs. */
                            path: string | null;
                            /** @description Number of items shown per page. */
                            per_page: number;
                            /** @description Number of the last item in the slice. */
                            to: number | null;
                            /** @description Total number of items being paginated. */
                            total: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
        };
    };
    "campaigns.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `CampaignResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CampaignResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "campaigns.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The campaign ID */
                campaign: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `CampaignResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CampaignResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "campaigns.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The campaign ID */
                campaign: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateCampaignRequest"];
            };
        };
        responses: {
            /** @description `CampaignResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CampaignResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "campaigns.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The campaign ID */
                campaign: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        message: "Campaign deleted.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "campaigns.estimate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The campaign ID */
                campaign: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `CampaignResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CampaignResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "campaigns.schedule": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The campaign ID */
                campaign: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleCampaignRequest"];
            };
        };
        responses: {
            /** @description `CampaignResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CampaignResource"];
                    } | Record<string, never>;
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "campaigns.send": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The campaign ID */
                campaign: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `CampaignResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CampaignResource"];
                    } | Record<string, never>;
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "campaigns.cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The campaign ID */
                campaign: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `CampaignResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CampaignResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "campaigns.stats": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The campaign ID */
                campaign: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `CampaignStatsResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CampaignStatsResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        message: "Stats not yet available.";
                        available_at: string;
                    } | {
                        /** @enum {string} */
                        message: "Stats not yet available.";
                        available_at: null;
                    } | {
                        /** @enum {string} */
                        message: "Stats only available for sent campaigns.";
                    };
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        message: "Stats retrieval failed.";
                    };
                };
            };
        };
    };
    "campaigns.export": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The campaign ID */
                campaign: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        message: "Only sent campaigns can be exported.";
                    };
                };
            };
        };
    };
    "interestGroups.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `InterestGroupResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["InterestGroupResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "partner-pricings.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `PartnerPricingResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PartnerPricingResource"][];
                        links: {
                            first: string | null;
                            last: string | null;
                            prev: string | null;
                            next: string | null;
                        };
                        meta: {
                            current_page: number;
                            from: number | null;
                            last_page: number;
                            /** @description Generated paginator links. */
                            links: {
                                url: string | null;
                                label: string;
                                active: boolean;
                            }[];
                            /** @description Base path for paginator generated URLs. */
                            path: string | null;
                            /** @description Number of items shown per page. */
                            per_page: number;
                            /** @description Number of the last item in the slice. */
                            to: number | null;
                            /** @description Total number of items being paginated. */
                            total: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
        };
    };
    "partner-pricings.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StorePartnerPricingRequest"];
            };
        };
        responses: {
            /** @description `PartnerPricingResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PartnerPricingResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "partner-pricings.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The partner pricing ID */
                partnerPricing: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `PartnerPricingResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PartnerPricingResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "partner-pricings.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The partner pricing ID */
                partnerPricing: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdatePartnerPricingRequest"];
            };
        };
        responses: {
            /** @description `PartnerPricingResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PartnerPricingResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "partner-pricings.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The partner pricing ID */
                partnerPricing: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        message: "Partner pricing deleted.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "partners.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `PartnerResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PartnerResource"][];
                        links: {
                            first: string | null;
                            last: string | null;
                            prev: string | null;
                            next: string | null;
                        };
                        meta: {
                            current_page: number;
                            from: number | null;
                            last_page: number;
                            /** @description Generated paginator links. */
                            links: {
                                url: string | null;
                                label: string;
                                active: boolean;
                            }[];
                            /** @description Base path for paginator generated URLs. */
                            path: string | null;
                            /** @description Number of items shown per page. */
                            per_page: number;
                            /** @description Number of the last item in the slice. */
                            to: number | null;
                            /** @description Total number of items being paginated. */
                            total: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
        };
    };
    "partners.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StorePartnerRequest"];
            };
        };
        responses: {
            /** @description `PartnerResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PartnerResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "partners.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The partner ID */
                partner: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `PartnerResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PartnerResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "partners.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The partner ID */
                partner: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdatePartnerRequest"];
            };
        };
        responses: {
            /** @description `PartnerResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PartnerResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "partners.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The partner ID */
                partner: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        message: "Partner deleted.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "shops.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `ShopResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ShopResource"][];
                        links: {
                            first: string | null;
                            last: string | null;
                            prev: string | null;
                            next: string | null;
                        };
                        meta: {
                            current_page: number;
                            from: number | null;
                            last_page: number;
                            /** @description Generated paginator links. */
                            links: {
                                url: string | null;
                                label: string;
                                active: boolean;
                            }[];
                            /** @description Base path for paginator generated URLs. */
                            path: string | null;
                            /** @description Number of items shown per page. */
                            per_page: number;
                            /** @description Number of the last item in the slice. */
                            to: number | null;
                            /** @description Total number of items being paginated. */
                            total: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
        };
    };
    "shops.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `ShopResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ShopResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "shops.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The shop ID */
                shop: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `ShopResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ShopResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "shops.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The shop ID */
                shop: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateShopRequest"];
            };
        };
        responses: {
            /** @description `ShopResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ShopResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "shops.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The shop ID */
                shop: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        message: "Shop deleted.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "users.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `UserResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserResource"][];
                        links: {
                            first: string | null;
                            last: string | null;
                            prev: string | null;
                            next: string | null;
                        };
                        meta: {
                            current_page: number;
                            from: number | null;
                            last_page: number;
                            /** @description Generated paginator links. */
                            links: {
                                url: string | null;
                                label: string;
                                active: boolean;
                            }[];
                            /** @description Base path for paginator generated URLs. */
                            path: string | null;
                            /** @description Number of items shown per page. */
                            per_page: number;
                            /** @description Number of the last item in the slice. */
                            to: number | null;
                            /** @description Total number of items being paginated. */
                            total: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
        };
    };
    "users.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreUserRequest"];
            };
        };
        responses: {
            /** @description `UserResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "users.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The user ID */
                user: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `UserResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "users.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The user ID */
                user: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description `UserResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "users.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The user ID */
                user: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        message: "User deleted.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
}
