import { beforeEach, describe, expect, it, vi } from 'vitest'
import { computed, ref } from 'vue'
import { stubContentApi, stubEditorConfig, stubLocalStorageService } from '../../helpers/stubs'

// Stub Vue reactivity
vi.stubGlobal('ref', ref)
vi.stubGlobal('computed', computed)

// Stub VueUse debounce — call the fn directly (no delay)
vi.stubGlobal('useDebounceFn', (fn: (...args: any[]) => any) => fn)

// Stub constants (auto-imported)
vi.stubGlobal('AUTOSAVE_DEBOUNCE_MS', 3000)
vi.stubGlobal('LOCAL_SAVE_DEBOUNCE_MS', 1000)
vi.stubGlobal('AUTOSAVE_SUCCESS_MESSAGE_MS', 2000)
vi.stubGlobal('AUTOSAVE_ERROR_MESSAGE_MS', 3000)

// Mock stores
const mockEditorStore = {
  isDirty: false,
  design: { version: '1.0', globalStyles: {}, widgets: [] },
  markAsSaved: vi.fn(),
  markAsDirty: vi.fn(),
}
const mockWidgetsStore = {
  items: [] as any[],
}
const mockContentStore = {
  id: null as number | null,
  type: 'landing-page' as string | null,
  title: '',
  setMetadata: vi.fn(),
}
const mockToast = {
  info: vi.fn(),
  success: vi.fn(),
  error: vi.fn(),
  warning: vi.fn(),
}

vi.stubGlobal('useEditorStore', () => mockEditorStore)
vi.stubGlobal('useWidgetsStore', () => mockWidgetsStore)
vi.stubGlobal('useContentStore', () => mockContentStore)
vi.stubGlobal('useToast', () => mockToast)

// Stub watch to no-op (we test actions directly, not the watcher)
vi.stubGlobal('watch', vi.fn())

const _config = stubEditorConfig()
const contentApi = stubContentApi()
const localStore = stubLocalStorageService()

// Mock shared utils
vi.mock('#shared/utils/content', () => ({
  generateContentName: vi.fn(() => 'Landing page - 15 jan. 14:32'),
  isAutoGeneratedName: vi.fn((title: string) => {
    return /^(?:Landing page|Message RCS|SMS) - \d/.test(title) || title === 'Sans titre' || title === ''
  }),
}))

const { useAutoSave, resetRenameToastState } = await import('#editor/composables/useAutoSave')

describe('useAutoSave', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    vi.useRealTimers()
    mockEditorStore.isDirty = false
    mockEditorStore.design = { version: '1.0', globalStyles: {}, widgets: [] }
    mockContentStore.id = null
    mockContentStore.type = 'landing-page'
    mockContentStore.title = ''
    mockWidgetsStore.items = []
    resetRenameToastState()
  })

  function createAutoSave(options = {}) {
    return useAutoSave(options)
  }

  describe('initial state', () => {
    it('has saveStatus idle', () => {
      const { saveStatus } = createAutoSave()
      expect(saveStatus.value).toBe('idle')
    })

    it('has lastError null', () => {
      const { lastError } = createAutoSave()
      expect(lastError.value).toBeNull()
    })

    it('has lastSyncedAt null', () => {
      const auto = createAutoSave()
      expect(auto.lastSyncedAt.value).toBeNull()
    })
  })

  describe('needsFirstSave', () => {
    it('returns true when contentStore.id is null', () => {
      mockContentStore.id = null
      const { needsFirstSave } = createAutoSave()
      expect(needsFirstSave.value).toBe(true)
    })

    it('returns false when contentStore.id is set', () => {
      mockContentStore.id = 42
      const { needsFirstSave } = createAutoSave()
      expect(needsFirstSave.value).toBe(false)
    })
  })

  describe('saveNow', () => {
    it('returns false if no contentId', async () => {
      mockContentStore.id = null
      const { saveNow } = createAutoSave()
      const result = await saveNow()
      expect(result).toBe(false)
    })

    it('calls saveDesign on success', async () => {
      mockContentStore.id = 10
      contentApi.saveDesign.mockResolvedValue({ success: true, id: 10, updatedAt: '2025-01-01' })

      const { saveNow, saveStatus } = createAutoSave()
      const result = await saveNow()

      expect(result).toBe(true)
      expect(contentApi.saveDesign).toHaveBeenCalledWith(10, expect.any(Object))
      expect(saveStatus.value).toBe('saved')
    })

    it('calls markAsSaved and clearBackup on success', async () => {
      mockContentStore.id = 10
      contentApi.saveDesign.mockResolvedValue({ success: true, id: 10, updatedAt: '2025-01-01' })

      const { saveNow } = createAutoSave()
      await saveNow()

      expect(mockEditorStore.markAsSaved).toHaveBeenCalled()
      expect(localStore.clearBackup).toHaveBeenCalledWith(10)
    })

    it('sets lastSyncedAt on success', async () => {
      mockContentStore.id = 10
      contentApi.saveDesign.mockResolvedValue({ success: true, id: 10, updatedAt: '2025-01-01' })

      const { saveNow, lastSyncedAt } = createAutoSave()
      await saveNow()

      expect(lastSyncedAt.value).toBeInstanceOf(Date)
    })

    it('sets lastError and status error on failure', async () => {
      mockContentStore.id = 10
      contentApi.saveDesign.mockResolvedValue(null)

      const { saveNow, saveStatus, lastError } = createAutoSave()
      const result = await saveNow()

      expect(result).toBe(false)
      expect(saveStatus.value).toBe('error')
      expect(lastError.value).toBeTruthy()
    })
  })

  describe('createAndSave', () => {
    it('calls createContent then performSave', async () => {
      contentApi.createContent.mockResolvedValue({ id: 99, type: 'landing-page', title: 'Test', status: 'DRAFT', createdAt: '', updatedAt: '' })
      contentApi.saveDesign.mockResolvedValue({ success: true, id: 99, updatedAt: '' })

      const { createAndSave } = createAutoSave()
      const result = await createAndSave('Test')

      expect(result.success).toBe(true)
      expect(result.id).toBe(99)
      expect(contentApi.createContent).toHaveBeenCalledWith({ type: 'landing-page', title: 'Test' })
      expect(contentApi.saveDesign).toHaveBeenCalledWith(99, expect.any(Object))
    })

    it('updates contentStore.setMetadata', async () => {
      mockContentStore.setMetadata = vi.fn()
      contentApi.createContent.mockResolvedValue({ id: 99, type: 'landing-page', title: 'Test', status: 'DRAFT', createdAt: '', updatedAt: '' })
      contentApi.saveDesign.mockResolvedValue({ success: true, id: 99, updatedAt: '' })

      const { createAndSave } = createAutoSave()
      await createAndSave('Test')

      expect(mockContentStore.setMetadata).toHaveBeenCalledWith({
        id: 99,
        type: 'landing-page',
        title: 'Test',
      })
    })

    it('returns { success: false } on creation error', async () => {
      contentApi.createContent.mockResolvedValue(null)

      const { createAndSave, saveStatus } = createAutoSave()
      const result = await createAndSave('Test')

      expect(result.success).toBe(false)
      expect(saveStatus.value).toBe('error')
    })
  })

  describe('handleSaveError', () => {
    it('sets lastError and status error', async () => {
      mockContentStore.id = 10
      contentApi.saveDesign.mockResolvedValue(null)

      const { saveNow, lastError, saveStatus } = createAutoSave()
      await saveNow()

      expect(lastError.value).toBe('Échec de la sauvegarde')
      expect(saveStatus.value).toBe('error')
    })

    it('auto-resets error status after timeout', async () => {
      vi.useFakeTimers()
      mockContentStore.id = 10
      contentApi.saveDesign.mockResolvedValue(null)

      const { saveNow, saveStatus } = createAutoSave()
      await saveNow()

      expect(saveStatus.value).toBe('error')

      await vi.advanceTimersByTimeAsync(3000)
      expect(saveStatus.value).toBe('idle')
    })
  })

  describe('saveToLocal', () => {
    it('calls localStorageService.saveBackup', () => {
      mockContentStore.id = 5
      mockEditorStore.isDirty = true

      const { saveToLocal } = createAutoSave()
      saveToLocal()

      expect(localStore.saveBackup).toHaveBeenCalledWith(5, expect.any(Object), true)
    })

    it('does nothing if no contentId', () => {
      mockContentStore.id = null

      const { saveToLocal } = createAutoSave()
      saveToLocal()

      expect(localStore.saveBackup).not.toHaveBeenCalled()
    })
  })

  describe('saveToApi', () => {
    it('does nothing if not dirty', async () => {
      mockContentStore.id = 10
      mockEditorStore.isDirty = false

      const { saveToApi } = createAutoSave()
      await saveToApi()

      expect(contentApi.saveDesign).not.toHaveBeenCalled()
    })

    it('does nothing if no contentId', async () => {
      mockContentStore.id = null
      mockEditorStore.isDirty = true

      const { saveToApi } = createAutoSave()
      await saveToApi()

      expect(contentApi.saveDesign).not.toHaveBeenCalled()
    })
  })

  describe('showRenameToast', () => {
    it('shows toast once for auto-generated title', () => {
      mockContentStore.title = 'Landing page - 15 jan. 14:32'

      const { showRenameToast } = createAutoSave()
      showRenameToast()

      expect(mockToast.info).toHaveBeenCalledTimes(1)
    })

    it('does not show toast twice (hasShownRenameToast)', () => {
      mockContentStore.title = 'Landing page - 15 jan. 14:32'

      const { showRenameToast } = createAutoSave()
      showRenameToast()
      showRenameToast()

      expect(mockToast.info).toHaveBeenCalledTimes(1)
    })

    it('does not show toast if title is not auto-generated', () => {
      mockContentStore.title = 'Mon super contenu'

      const { showRenameToast } = createAutoSave()
      showRenameToast()

      expect(mockToast.info).not.toHaveBeenCalled()
    })
  })

  describe('resetRenameToastState', () => {
    it('resets the flag so toast can be shown again', () => {
      mockContentStore.title = 'Landing page - 15 jan. 14:32'

      const { showRenameToast } = createAutoSave()
      showRenameToast()
      expect(mockToast.info).toHaveBeenCalledTimes(1)

      resetRenameToastState()

      showRenameToast()
      expect(mockToast.info).toHaveBeenCalledTimes(2)
    })
  })

  describe('status transitions', () => {
    it('saved status auto-resets after timeout', async () => {
      vi.useFakeTimers()
      mockContentStore.id = 10
      contentApi.saveDesign.mockResolvedValue({ success: true, id: 10, updatedAt: '' })

      const { saveNow, saveStatus } = createAutoSave()
      await saveNow()

      expect(saveStatus.value).toBe('saved')

      // saveNow doesn't use AUTOSAVE_SUCCESS_MESSAGE_MS timeout (only saveToApi does)
      // but the status stays at 'saved' until explicitly changed
    })
  })
})
