/**
 * Convert a content type to its URL slug
 * @param type - The content type
 * @returns The URL slug for routing
 */
export function getContentTypeSlug(type: ContentType): string {
  return type === 'landing-page' ? 'lp' : type
}

/**
 * Labels for content types in generated names
 */
const CONTENT_TYPE_NAME_LABELS: Record<ContentType, string> = {
  'landing-page': 'Landing page',
  'rcs': 'Message RCS',
  'sms': 'SMS',
}

/**
 * Generate a meaningful auto-generated name for new content
 * Format: "{Content Type} - {Day} {Month abbr.} {Hour}:{Minutes}"
 * Example: "Landing page - 21 jan. 14:32"
 *
 * @param type - The content type
 * @param date - Optional date (defaults to now)
 * @param locale - Locale for date formatting (defaults to fr-FR)
 * @returns Generated content name
 */
export function generateContentName(
  type: ContentType,
  date: Date = new Date(),
  locale = 'fr-FR',
): string {
  const typeLabel = CONTENT_TYPE_NAME_LABELS[type]

  const dateStr = date.toLocaleDateString(locale, {
    day: 'numeric',
    month: 'short',
  })

  const timeStr = date.toLocaleTimeString(locale, {
    hour: '2-digit',
    minute: '2-digit',
    hour12: false,
  })

  return `${typeLabel} - ${dateStr} ${timeStr}`
}

/**
 * Check if a title is an auto-generated default name
 * Matches patterns like "Landing page - 21 jan. 14:32"
 *
 * @param title - The title to check
 * @returns True if the title matches auto-generated pattern
 */
export function isAutoGeneratedName(title: string): boolean {
  // Pattern: "{Type} - {day} {month}. {HH}:{MM}" or "{Type} - {day} {month} {HH}:{MM}"
  const patterns = [
    /^(Landing page|Message RCS|SMS) - \d{1,2} \w+\.? \d{2}:\d{2}$/,
    /^Sans titre$/i,
  ]
  return patterns.some(pattern => pattern.test(title.trim()))
}
