import { localStorageService } from '../services/persistence/localStorage'

export type SaveStatus = 'idle' | 'pending' | 'saving' | 'saved' | 'error'

export interface AutoSaveOptions {
  debounceMs?: number
  localSaveMs?: number
  enabled?: boolean
  onFirstSaveComplete?: () => void
}

export interface AutoSaveReturn {
  saveStatus: Ref<SaveStatus>
  lastError: Ref<string | null>
  lastSyncedAt: Ref<Date | null>
  saveNow: () => Promise<boolean>
  saveToApi: () => void
  saveToLocal: () => void
  needsFirstSave: ComputedRef<boolean>
  createAndSave: (title: string) => Promise<{ success: boolean, id?: number }>
  showRenameToast: () => void
}

// Track if we've already shown the rename toast for this session
const hasShownRenameToast = ref(false)

export function useAutoSave(options: AutoSaveOptions = {}): AutoSaveReturn {
  const {
    debounceMs = AUTOSAVE_DEBOUNCE_MS,
    localSaveMs = LOCAL_SAVE_DEBOUNCE_MS,
    enabled = true,
    onFirstSaveComplete,
  } = options

  const config = useEditorConfig()
  const contentApi = useContentApi()
  const editorStore = useEditorStore()
  const widgetsStore = useWidgetsStore()
  const contentStore = useContentStore()
  const toast = useToast()

  // Track if we're currently creating a new content to prevent duplicate calls
  const isCreatingNew = ref(false)

  const saveStatus = ref<SaveStatus>('idle')
  const lastError = ref<string | null>(null)
  const lastSyncedAt = ref<Date | null>(null)

  const currentDocument = computed<DesignDocument>(() => ({
    version: editorStore.design.version,
    globalStyles: editorStore.design.globalStyles,
    widgets: widgetsStore.items,
  }))

  const hasContentId = computed(() => contentStore.id !== null)

  /**
   * Core save operation - shared between saveToApi and saveNow
   */
  async function performSave(contentId: number): Promise<boolean> {
    const result = await contentApi.saveDesign(contentId, currentDocument.value)

    if (!result) {
      throw new Error('Échec de la sauvegarde')
    }

    editorStore.markAsSaved()
    localStorageService.clearBackup(contentId)
    lastSyncedAt.value = new Date()
    return true
  }

  /**
   * Handle save error
   */
  function handleSaveError(error: unknown): void {
    lastError.value = error instanceof Error ? error.message : 'Erreur inconnue'
    saveStatus.value = 'error'

    setTimeout(() => {
      if (saveStatus.value === 'error') {
        saveStatus.value = 'idle'
      }
    }, AUTOSAVE_ERROR_MESSAGE_MS)
  }

  /**
   * Show a toast inviting user to rename their content
   */
  function showRenameToast() {
    if (hasShownRenameToast.value)
      return

    // Only show if the name is still auto-generated
    if (!isAutoGeneratedName(contentStore.title))
      return

    hasShownRenameToast.value = true

    toast.info(
      'Cliquez sur le titre dans la barre d\'outils pour le personnaliser.',
      {
        title: 'Contenu enregistré',
        duration: 8000,
        actions: [
          {
            label: 'Renommer',
            variant: 'primary',
            onClick: () => {
              onFirstSaveComplete?.()
            },
          },
          {
            label: 'Plus tard',
            variant: 'secondary',
            onClick: () => {
              // Just dismiss
            },
          },
        ],
      },
    )
  }

  const saveToApi = useDebounceFn(async () => {
    if (!editorStore.isDirty || !hasContentId.value)
      return

    const contentId = contentStore.id!

    saveStatus.value = 'saving'
    lastError.value = null

    try {
      await performSave(contentId)
      saveStatus.value = 'saved'

      setTimeout(() => {
        if (saveStatus.value === 'saved') {
          saveStatus.value = 'idle'
        }
      }, AUTOSAVE_SUCCESS_MESSAGE_MS)
    }
    catch (error) {
      handleSaveError(error)
    }
  }, debounceMs)

  const saveToLocal = useDebounceFn(() => {
    const id = contentStore.id
    if (!id)
      return

    localStorageService.saveBackup(id, currentDocument.value, editorStore.isDirty)
  }, localSaveMs)

  watch(
    () => [editorStore.isDirty, widgetsStore.items],
    async () => {
      if (!enabled)
        return

      if (!editorStore.isDirty)
        return

      // If new content (no ID), create it first then save
      if (!hasContentId.value) {
        if (isCreatingNew.value)
          return // Already creating, skip

        isCreatingNew.value = true

        // Use auto-generated name instead of "Sans titre"
        const autoTitle = contentStore.title && !isAutoGeneratedName(contentStore.title)
          ? contentStore.title
          : generateContentName(contentStore.type || 'landing-page')

        const result = await createAndSave(autoTitle)

        if (result.success && result.id) {
          config.onContentCreated?.(result.id)

          // Show rename toast after a short delay
          setTimeout(() => {
            showRenameToast()
          }, 1500)
        }

        isCreatingNew.value = false
        return
      }

      // Normal auto-save for existing content
      saveStatus.value = 'pending'
      saveToLocal()
      saveToApi()
    },
    { deep: true },
  )

  async function saveNow(): Promise<boolean> {
    if (!hasContentId.value)
      return false

    const contentId = contentStore.id!
    saveStatus.value = 'saving'

    try {
      await performSave(contentId)
      saveStatus.value = 'saved'
      return true
    }
    catch (error) {
      handleSaveError(error)
      return false
    }
  }

  const needsFirstSave = computed(() => !hasContentId.value)

  async function createAndSave(title: string): Promise<{ success: boolean, id?: number }> {
    saveStatus.value = 'saving'
    lastError.value = null

    try {
      const created = await contentApi.createContent({
        type: contentStore.type || 'landing-page',
        title,
      })

      if (!created) {
        throw new Error('Échec de la création du contenu')
      }

      contentStore.setMetadata({
        id: created.id,
        type: contentStore.type || 'landing-page',
        title: created.title,
      })

      await performSave(created.id)
      saveStatus.value = 'saved'

      return { success: true, id: created.id }
    }
    catch (error) {
      handleSaveError(error)
      return { success: false }
    }
  }

  return {
    saveStatus,
    lastError,
    lastSyncedAt,
    saveNow,
    saveToApi,
    saveToLocal,
    needsFirstSave,
    createAndSave,
    showRenameToast,
  }
}

/**
 * Reset the toast shown state (useful for testing or when user logs out)
 */
export function resetRenameToastState() {
  hasShownRenameToast.value = false
}
